baseURL: "https://accioly.dev/"
title: Anthony Accioly
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: G-XJ49WZ8741

pagination:
    pagerSize: 5

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Anthony Accioly
    description: "My Blog"
    keywords: [Blog]
    author: Anthony Accioly
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "02 Jan 06 15:04 MST"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        #favicon: "<link / abs url>"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: Anthony Accioly
        subtitle: "This is my profile"
        imageUrl: "#"
        #imageWidth: 120
        #imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            Welcome to my blog

            - It's still under construction, but I do have big plans for it!

            -

            - If you want something to read right now, check out:

            -

            - **🌐 [https://a.accioly.7rtc.com](https://a.accioly.7rtc.com)**

            - My old blog in Brazilian Portuguese.

            - It has one of those old school Google Translator widgets!

            - The automatic translation isn't really any good. But...

            - You know, 2000's technology is brilliant!

            -

            - **🌐 [https://7rtc.com](https://7rtc.com)**

            - I also plan to do something with my company's domain one day.

            - But for now it's website is redirecting to LinkedIn 🙈.

            -

            - Finally, feel free to follow me on:

    socialIcons:
        - name: github
          url: "https://github.com/aaccioly"
        - name: keybase
          url: "https://keybase.io/aaccioly"
        - name: linkedin
          url: "https://www.linkedin.com/in/aaccioly"
        - name: mastodon
          url: "https://accioly.social/@anthony"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/664577/anthony-accioly"
        - name: rss
          url: "index.xml"
    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/aaccioly/accioly-dev/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: 7rtc
          name: 7rtc.com
          url: https://7rtc.com
          weight: 30
        - identifier: old-blog
          name: My old blog (pt-BR)
          url: https://a.accioly.7rtc.com
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
